version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      minor-and-patch:
        update-types:
        - "minor"
        - "patch"
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
        exclude-patterns:
        - "rollup*"
        - "@rollup*"
      rollup:
        patterns:
        - "rollup*"
        - "@rollup*"