version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      build-dependencies:
        dependency-type: "development"
        patterns:
          - "rollup*"
          - "@rollup*"
      development-dependencies:
        dependency-type: "development"